ASP MVC Entity CRUD Modal Bootstrap/Models/DBmodel.cs
namespace ASP_MVC_Entity_CRUD_Modal_Bootstrap.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;

    public class DBmodel : DbContext
    {
        public DBmodel() : base("name=DBmodel")
        {
        }
       
        public virtual DbSet<MyEntity> MyEntities { get; set; }
    }

    public class MyEntity
    {
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string SecondName { get; set; }
        public string PhoneNumber { get; set; }
        [EmailAddress]
        public string Email { get; set; }
    }
}

ASP MVC Entity CRUD Modal Bootstrap/Controllers/MyEntitiesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ASP_MVC_Entity_CRUD_Modal_Bootstrap.Models;

namespace ASP_MVC_Entity_CRUD_Modal_Bootstrap.Controllers
{
    public class MyEntitiesController : Controller
    {
        private DBmodel db = new DBmodel();

        // GET: MyEntities/Index
        public ActionResult Index()
        {
            return View(db.MyEntities.ToList());
        }

        // GET: MyEntities/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,SecondName,PhoneNumber,Email")] MyEntity myEntity)
        {
            if (ModelState.IsValid)
            {
                db.MyEntities.Add(myEntity);
                db.SaveChanges();
                return Json(myEntity);
            }
            return Json("Create error");
        }

        //GET: MyEntities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyEntity myEntity = db.MyEntities.Find(id);
            if (myEntity == null)
            {
                return HttpNotFound();
            }
            return PartialView(myEntity);
        }

        //POST: MyEntities/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,SecondName,PhoneNumber,Email")] MyEntity myEntity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(myEntity).State = EntityState.Modified;
                db.SaveChanges();
                return Json(myEntity);
            }
            return Json("Edit error");
        }

        //GET: MyEntities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyEntity myEntity = db.MyEntities.Find(id);
            if (myEntity == null)
            {
                return HttpNotFound();
            }
            return PartialView(myEntity);
        }

        //POST: MyEntities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MyEntity myEntity = db.MyEntities.Find(id);
            db.MyEntities.Remove(myEntity);
            return Json(db.SaveChanges());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ASP MVC Entity CRUD Modal Bootstrap/Views/MyEntities/Create.cshtml
@model ASP_MVC_Entity_CRUD_Modal_Bootstrap.Models.MyEntity

<div class="modal-header">
    <button class="btn btn-sm pull-right btn-danger" type="button" id="btnCloseModal" data-dismiss="modal">X</button>
    <h2>Create</h2>
</div>
<div class="modal-body">
    @using (Html.BeginForm())
    {
        <div class="form-horizontal" id="CreateForm">
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-5">
                    <input class="form-control" type="text" name="FirstName" id="FirstName" placeholder="required" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SecondName, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-5">
                    <input class="form-control" type="text" name="SecondName" id="SecondName" placeholder="required" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-5">
                    <input class="form-control" type="tel" name="PhoneNumber" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-5">
                    <input class="form-control" type="email" name="Email" id="Email" placeholder="Enter email address" />
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-sm btn-success" type="button" onclick="CreateNew()">Save</button>
        </div>
    }
</div>

ASP MVC Entity CRUD Modal Bootstrap/Views/MyEntities/Delete.cshtml
@model ASP_MVC_Entity_CRUD_Modal_Bootstrap.Models.MyEntity

<div class="modal-header">
    <button class="btn btn-sm pull-right btn-danger" type="button" id="btnCloseModal" data-dismiss="modal">X</button>
    <h3>Are you sure you want to delete this?</h3>
</div>
<div class="modal-body">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>

    @using (Html.BeginForm("Delete", "MyEntities", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="modal-footer">
            <button type="button" onclick="DeleteEmp(@Model.Id)" class="btn btn-sm btn-success">Delete</button>
        </div>
    }

</div>

ASP MVC Entity CRUD Modal Bootstrap/Views/MyEntities/Edit.cshtml
@model ASP_MVC_Entity_CRUD_Modal_Bootstrap.Models.MyEntity

<div class="modal-header">
    <button class="btn btn-sm pull-right btn-danger" type="button" id="btnCloseModal" data-dismiss="modal">X</button>
    <h2>Edit</h2>
</div>
<div class="modal-body">
    @using (Html.BeginForm("Edit", "MyEntities", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SecondName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SecondName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-success" onclick="EditEmp(@Model.Id)">Save changes</button>
        </div>
    }
</div>

ASP MVC Entity CRUD Modal Bootstrap/Views/MyEntities/Index.cshtml
@model IEnumerable<ASP_MVC_Entity_CRUD_Modal_Bootstrap.Models.MyEntity>
@{
    ViewBag.Title = "Main";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    <button type="button" class="btn btn-sm btn-success" data-toggle="modal" onclick="RenderActions('/MyEntities/Create')" data-target="#modalCreate">Create new</button>
</p>
<table class="table" id="tableMain">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SecondName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>
    <tbody id="indexTbody">
        @foreach (var item in Model)
        {
            <tr id="@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SecondName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <button class="btn btn-sm btn-primary" data-toggle="modal" onclick="RenderActions('/MyEntities/Edit/' + @item.Id)" data-target="#modalCreate">Edit</button> | 
                    <button class="btn btn-sm btn-danger" data-toggle="modal" onclick="RenderActions('/MyEntities/Delete/' + @item.Id)" data-target="#modalCreate">Delete</button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div id="modalCreate" class="modal fade" role="dialog" data-backdrop="false" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="OpenDialog" class="modal-body">
            </div>
        </div>
    </div>
</div>

ASP MVC Entity CRUD Modal Bootstrap/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Leving CRUD</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/mainjs")
    @RenderSection("scripts", required: false)
</body>
</html>